### ISSUE TITLE
Full docker-compose example

### ISSUE THREAD

**Issue by ansgarschulte** [mettke/ssh-key-authority#4]
Hi,

do you have a full docker compose example with your Docker Hub Image available?
Or is this sufficient?

```
version: "3"

services:
  ska-db:
    image: mariadb
    container_name: ska-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ska-db
      - MYSQL_USER=ska-user
      - MYSQL_PASSWORD=password
    volumes:
      - ./db:/var/lib/mysql:rw
    networks:
      - proxy
  ska:
    image: toendeavour/ssh-key-authority
    container_name: ska
    restart: always
    ports:
      - "8088:80"
    depends_on:
      - ska-db
    volumes:
      - ./config:/ska/config
    networks:
      - proxy


networks:
  proxy:
    external: true


```
